package com.makomi.config;

/**
 * 基础运行时配置快照。
 */
record RedstoneLinkConfigValues(
	int pulseDurationTicks,
	RedstoneLinkConfig.EmitterEdgeMode emitterEdgeMode,
	int coreOutputPower,
	int maxTargetsPerSetLinks,
	boolean allowOfflineTargetBinding,
	int commandPermissionLevel,
	int otherCommandPermissionLevel,
	boolean commandBenchmarkModeEnabled,
	boolean commandInputEnabled,
	boolean commandNodeTraceEnabled,
	boolean runtimeCoreLoadResyncEnabled,
	boolean runtimeTriggerSourceLoadResyncEnabled,
	int runtimeLoadResyncMaxRetry,
	boolean commandRateLimitEnabled,
	int commandRateLimitWindowTicks,
	int commandRateLimitGlobalCapacity,
	int commandRateLimitTierBaseCapacity,
	int commandRateLimitTierStepPerLevel,
	int commandRateLimitActorBaseCapacity,
	int commandRateLimitActorStepPerLevel,
	int commandRateLimitActorGroupLinkRwBaseCapacity,
	int commandRateLimitActorGroupLinkRwStepPerLevel,
	int commandRateLimitActorGroupCrossChunkBaseCapacity,
	int commandRateLimitActorGroupCrossChunkStepPerLevel,
	int commandRateLimitActorGroupOtherBaseCapacity,
	int commandRateLimitActorGroupOtherStepPerLevel,
	RedstoneLinkConfig.CurrentLinksPrivacyMode currentLinksPrivacyMode,
	int currentLinksPrivacyViewPermissionLevel,
	int currentLinksPrivacyManagePermissionLevel,
	RedstoneLinkConfig.LinkWriteControlMode linkWriteControlMode,
	int linkWriteLimitedPermissionLevel,
	int linkWriteLimitedMaxSetSize,
	int linkWriteProtectedPermissionLevel,
	int linkWriteProtectedManagePermissionLevel,
	int linkSetMaxInputLength,
	int activateBatchMaxSerials,
	int retireBatchMaxSerials,
	int currentLinksMaskSetMaxSerials,
	int writeControlProtectedSetMaxSerials,
	int crossChunkWhitelistSetMaxSerials,
	boolean requireSneakToOpenPairing,
	boolean requireSneakToOpenLinkerPairing,
	boolean requireEmptyOffhandToOpenPairing
) {
	/**
	 * @return 基础配置默认值
	 */
	static RedstoneLinkConfigValues defaults() {
		return new RedstoneLinkConfigValues(
			4,
			RedstoneLinkConfig.EmitterEdgeMode.RISING,
			15,
			1024,
			true,
			0,
			2,
			false,
			true,
			true,
			true,
			true,
			40,
			true,
			20,
			1024,
			96,
			64,
			24,
			16,
			12,
			8,
			4,
			3,
			6,
			4,
			RedstoneLinkConfig.CurrentLinksPrivacyMode.PLAIN,
			2,
			2,
			RedstoneLinkConfig.LinkWriteControlMode.LIMITED,
			2,
			64,
			2,
			2,
			1024,
			1024,
			1024,
			1024,
			1024,
			1024,
			true,
			true,
			true
		);
	}
}
